### ISSUE TITLE
Zombier løber efter spiller (4 timer)

### ISSUE THREAD

**Issue by Simon220902** [jegkanikkeheddemike/EksamensProjekt#30]
Zombierne skal fungere lidt ligesom spillere ift. hvordan de orienterer sig, men de kan kun bevæge sig ligeud.
Når zombier har fået øje på spiller skal de jagte spilleren ved at løbe i spillerens retning (der hvor de sidst har sanset spilleren).

**Comment by jegkanikkeheddemike** [comment]
2 timer
