### ISSUE TITLE
Zombier skal kunne få øje på spilleren (4 timer)

### ISSUE THREAD

**Issue by Simon220902** [jegkanikkeheddemike/EksamensProjekt#33]
Zombier skal kunne "se" spilleren ved at den har en bestemt synsvinkel og en synslængde.
Derudover skal vægge kunne stå "i vejen" for synet.
Når zombien ser spilleren skal den kunne huske hvilken retning spilleren var i. Hvorefter den bevæger sig i denne retning.

**Comment by jegkanikkeheddemike** [comment]
1.5 timer
