### ISSUE TITLE
Zombier skal kunne høre spilleren (4 timer)

### ISSUE THREAD

**Issue by Simon220902** [jegkanikkeheddemike/EksamensProjekt#34]
Zombien skal kunne høre spilleren ved at den har en høre range (en cirkel med zombien som centrum).
Hvor når spilleren bevæger sig vil det lave noget larm (endnu en cirkel), der når den skær zombiens høre range vil zombien vide hvor den skar og gå efter dette punkt.
Synssansen skal dog vægtes højere end høresansen.

**Comment by jegkanikkeheddemike** [comment]
1 time
