### ISSUE TITLE
Fjender spawnes på mappet i grupper (4 timer)

### ISSUE THREAD

**Issue by Simon220902** [jegkanikkeheddemike/EksamensProjekt#38]
Fjender (zombier) skal spawnes på mappet i takt med det genereres, hvor de spawnes i mindre gruppe dog  stadig lidt adspredt.
De skal spawnes som man ville forvente ift. hvilket område det er.
Da skal altså være zombies i huse, parker, parkeringspladser og i mindre grad på vejen.

**Comment by toreseb** [comment]
4 Timer
