### ISSUE TITLE
Zombier skal opføre sig forskelligt hver især (2 timer)

### ISSUE THREAD

**Issue by Simon220902** [jegkanikkeheddemike/EksamensProjekt#39]
Zombierne skal have en række attributter, der kan skrues på så de kommer til at opføre sig forskelligt.
Disse attributter er:
- Hastighed
- Høre-range(radius på høre cirkel)
- Synsvinkel og synslængde
- Melee eller range eller melee og range (altså om de kan slå eller kaste)
- Melee styrke

**Comment by jegkanikkeheddemike** [comment]
2.5 timer
